# Generated by Django 5.0 on 2023-12-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('employee_email', models.CharField(max_length=30)),
                ('password1', models.CharField(max_length=200)),
            ],
        ),
    ]
