# Generated by Django 5.0 on 2023-12-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0002_rename_employee_info_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='employee_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
